version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: flyway_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flyway_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - flyway_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: flyway_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - flyway_network

  # mailhog:
  #   image: mailhog/mailhog:latest
  #   container_name: flyway_mailhog
  #   ports:
  #     - "1025:1025"  # SMTP server
  #     - "8025:8025"  # Web UI
  #   networks:
  #     - flyway_network

volumes:
  mysql_data:

networks:
  flyway_network:
    driver: bridge

